server:
  port: 8181
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 500m
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: root
    url: jdbc:postgresql://localhost:5432/socialmedia
    username: root
    password: 123
    driverClassName: org.postgresql.Driver
  main:
    allow-circular-references: true